=== hfreye/RLP-XML/fachtype.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://bsbb.eu"
           xmlns="http://bsbb.eu"
           elementFormDefault="qualified">

<xs:include schemaLocation="http://bsbb.eu/textcontent.xsd"></xs:include>
<xs:include schemaLocation="http://bsbb.eu/c2type.xsd"></xs:include>

    <xs:complexType name="themainhalttype">
        <xs:sequence>
            <xs:element name="id" type="stringtype"/>
            <xs:element name="title" type="stringtype"/>
            <xs:element name="content" type="stringtype"
                        minOccurs="0"
                        maxOccurs="20"/>
            <xs:element name="inhalt" type="themainhalttype"
                        minOccurs="0"
                        maxOccurs="20"/>
        </xs:sequence>
    </xs:complexType>

   <xs:complexType name="c3type">
       <xs:sequence>
           <xs:element name="id" type="stringtype"/>
           <xs:element name="title" type="stringtype"/>
           <xs:element name="vortext" type="textcontent"/>
           <xs:element name="themainhalt" type="themainhalttype"
                       minOccurs="1"
                       maxOccurs="30"/>
       </xs:sequence>
   </xs:complexType>

    <xs:complexType name="fachtype">
        <xs:sequence>
            <xs:element name="id" type="stringtype"/>
            <xs:element name="title" type="stringtype"/>
            <xs:element name="c1" type="textcontent"/>
            <xs:element name="c2" type="c2type"/>
            <xs:element name="c3" type="c3type"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="fach" type="fachtype"/>

</xs:schema>

=== hfreye/RLP-XML/sowiwiwi.xml
<?xml version="1.0" encoding="UTF-8"?>
<fach xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xmlns="http://bsbb.eu" 
	xsi:schemaLocation="http://bsbb.eu fachtype.xsd">

<id>C-SOWI</id>
	<title>Sozialwissenschaft/Wirtschaftswissenschaft</title>
	<c1>
		<id>C-SOWI-1</id>
		<title>Kompetenzentwicklung im Fach Sozialwissenschaften/Wirtschaftswissenschaft</title>
		<subtext>
			<id>C-SOWI-1-1</id>
			<title>Ziele des Unterrichts</title>
			<content>Das Wahlpflichtfach Sozialwissenschaften/Wirtschaftswissenschaft bietet Schülerinnen und Schülern die Möglichkeit, anknüpfend an den Unterricht der Fächer Politische Bildung und Ethik, sozialwissenschaftliche Kompetenzen zu erweitern und zu vertiefen. Es integriert die Teilgebiete Wirtschaft, Recht und Soziologie und bereitet die Schülerinnen und Schüler auf den Unterricht in den Fächern Sozialwissenschaften, Wirtschaftswissenschaft und Recht in der gymnasialen Oberstufe vor.
Den Lernenden begegnet gesellschaftliche Komplexität in sozialen, rechtlichen und wirtschaftlichen Handlungszusammenhängen. Im Fach Sozialwissenschaften/Wirtschaftswissenschaft erschließen und analysieren die Schülerinnen und Schüler diese Zusammenhänge, die ihnen gegenüber sowohl vorgegeben als auch gestaltungsbedürftig erscheinen. Sie lernen, sich im gegenwärtigen gesellschaftlichen und wirtschaftlichen Geschehen zu orientieren, Perspektiven und Alternativen zu reflektieren, selbstständig und kriterienorientiert zu urteilen und eigene Handlungsmöglichkeiten abzuwägen. Damit fördert das Fach Sozialwissenschaften/Wirtschaftswissenschaft die eigene Identitätsfindung und versteht sich gleichermaßen als Grundlage für ein sozial verantwortliches Handeln sowie für die ökonomische, rechtliche und politische Mündigkeit der Lernenden.
Durch die Verknüpfung ökonomischer, sozialer und rechtlicher Aspekte wird eine hohe Anforderung in Bezug auf  multiperspektivisches Betrachten und vernetztes Denken gestellt, d. h., gesellschaftliche Fragen und Probleme werden in ihren interdependenten Zusammenhängen erkannt und beurteilt. Der Unterricht befähigt die Lernenden hierzu, indem sie herausgefordert sind, sozialwissenschaftliche Methoden (z. B. Methoden der qualitativen und quantitativen Sozialforschung, wie Interviews und Umfragen oder das Umgehen mit Statistiken) zu erproben und anzuwenden sowie gesellschaftliche Fragen und Probleme mithilfe soziologischer und wirtschaftswissenschaftlicher Theorien und Modelle zu erschließen.
Sozialwissenschaften/Wirtschaftswissenschaft bietet den Lernenden somit ein theoretisch fundiertes und anschlussfähiges Orientierungswissen sowie die Einführung in verschiedene Arbeitsweisen der gesellschaftswissenschaftlichen Fächer.


Teilgebiete Wirtschaft, Recht und Soziologie
Das Fach Sozialwissenschaften/Wirtschaftswissenschaft berücksichtigt schwerpunkmäßig Kompetenzen und die Auseinandersetzung mit Inhalten aus den Teilgebieten Wirtschaft, Recht und Soziologie. Die diesen Teilgebieten zugeordneten Themenfelder (vgl. Kapitel 3) zeichnen sich in ihrer Anordnung durch eine immanente Struktur aus, die der Lernprogression der Schülerinnen und Schüler Rechnung trägt, und führen auf die Anforderungen der gymnasialen Oberstufe hin. Es werden sowohl die jeweiligen wissenschaftlichen Besonderheiten dieser Teilgebiete als auch deren didaktische Integration berücksichtigt.
Sozialwissenschaftliches Denken in seiner soziologischen Dimension ist unter anderem dadurch charakterisiert, dass moderne Gesellschaften in allen ihren Teilbereichen durch Men-schen gestaltet werden. In seiner ökonomischen Dimension ist das sozialwissenschaftliche Denken unter anderem durch das Knappheits- und Rationalitätsprinzip charakterisiert. In seiner rechtlichen Dimension basiert es auf den Prinzipien des demokratisch verfassten Rechtsstaates.
Diese Denkweisen bieten in ihrer unterschiedlichen Zugriffsweise zahlreiche Anknüpfungspunkte für die Kooperation mit anderen Fächern und führen zu einer vertieften gesellschaftspolitischen Bildung.
</content>
		</subtext>
		<subtext>
			<id>C-SOWI-1-2</id>
			<title>Fachbezogene Kompetenzen</title>
			<content>Die Schülerinnen und Schüler erwerben im Fach Sozialwissenschaften/Wirtschaftswissenschaft grundlegende Handlungskompetenzen, die zur Entwicklung sozialer Verantwortung und ökonomischer, rechtlicher und politischer Mündigkeit beitragen. Die Handlungs-kompetenzen beruhen auf Kompetenzen des sozialwissenschaftlichen Analysierens und Urteilens und der Anwendung sozialwissenschaftlicher Methoden, die in der Auseinander-setzung mit den Teilgebieten des Faches erworben werden.</content>
		<title>Sozialwissenschaftliche Handlungskompetenz</title>
		<content>Sozialwissenschaftliche Handlungskompetenz zeigt sich in der Fähigkeit, erworbene Kompetenzen des Analysierens und Urteilens sowie der Anwendung sozialwissenschaftlicher Methoden in unterschiedlichen Handlungssituationen einsetzen zu können. Sie umfasst die Fähigkeit, Prozesse der soziologischen, ökonomischen und rechtlichen Meinungsbildung, Entscheidungsfindung und Umsetzung reflektiert zu beurteilen und entscheiden zu können, welche Optionen für das eigene Handeln bestehen. Dazu wenden die Lernenden u. a. diskursive und simulative Methoden der Handlungsorientierung an (z. B. einfache Szenarien, Entscheidungsspiele, Debatte) oder sie setzen kleinere Projekte um, in denen soziologische, rechtliche und wirtschaftswissenschaftliche Fragestellungen vernetzt betrachtet werden. Das ermöglicht den Schülerinnen und Schülern, Chancen der Einflussnahme auf die Gestaltung sozialer, wirtschaftlicher und rechtlicher Prozesse und Strukturen wahrzunehmen und zu 
erproben.</content>
		<title>Analysieren</title>
		<content>Sozialwissenschaftliches Analysieren (z. B. im Teilgebiet Recht mithilfe der Subsumtion oder die Analyse volkswirtschaftlicher Indikatoren oder soziologischer Theorien) bedeutet, dass die Schülerinnen und Schüler gesellschaftliche, ökonomische und rechtliche Strukturen und Prozesse erschließen und ihre Kenntnisse anwenden. Indem gesellschaftliche Fragen und Probleme mithilfe sozialwissenschaftlicher Perspektiven, Erklärungsmuster, Modelle und Theorien erschlossen werden, bildet die Analysekompetenz zugleich die Grundlage der sozialwissenschaftlichen Urteilsbildung.</content>
		<title>Methoden anwenden</title>
		<content>Die Anwendung sozialwissenschaftlicher Methoden umfasst die fachspezifischen Fähigkeiten und Fertigkeiten, die neben überfachlichen methodischen Kompetenzen (Medienkompetenz, bildungssprachliche Handlungskompetenz) benötigt werden, um sich mit soziologischen, ökonomischen und rechtlichen Erscheinungen und Herausforderungen auseinandersetzen zu können. Sie ist ein wesentliches Element sozialwissenschaftlicher Wissenschaftspropädeutik. Methodenkompetenz zeigt sich durch die zunehmende Beherrschung von Verfahren der sozialwissenschaftlichen Informationsgewinnung und -auswertung (z. B. durch die Anwendung empirischer Methoden wie Interviews oder Umfragen oder die kritische Auswertung von Statistiken und Grafiken). Dazu erwerben die Schülerinnen und Schüler Kompetenzen der sozialwissenschaftlichen Begriffs-, Hypothesen- und Modellbildung, die zugleich Grundlage sozialwissenschaftlichen Analysierens sind.</content>
		<title>Urteilen</title>
		<content>Sozialwissenschaftliches Urteilen beinhaltet den Ansatz einer selbstständigen, begründeten und reflektierten Beurteilung und Bewertung soziologischer, ökonomischer und rechtlicher Prozesse und Strukturen. Urteilskompetenz schließt die Herausbildung eines fachlich begründeten eigenen Standpunkts ebenso ein wie ein verständigungsorientiertes und multiperspektivisches Abwägen der eigenen Position mit den Positionen anderer. 
Im Unterricht werden verschiedene und kontroverse Urteile entwickelt und diskutiert, die die gesellschaftliche Interessenvielfalt widerspiegeln. Die Akzeptanz der Schülerinnen und Schüler für die legitime Meinungsvielfalt in einer Demokratie wird durch einen kontroversen, problemorientierten Unterricht gefördert.</content>
		<title>Didaktische Prinzipien</title>
		<content>Der Lern- und Lehrprozess wird grundsätzlich so organisiert, dass er problemlösendes Denken in den soziologischen, rechtlichen und wirtschaftlichen Dimensionen fördert sowie den Schülerinnen und Schülern selbsttätiges, planendes und eigenverantwortliches Lernen ermöglicht. Um eigenständig Analyse- und Urteilsaufgaben zu bewältigen, sollten die Lernenden möglichst in Projekten und an außerschulischen Lernorten tätig werden. Leitende didaktische Prinzipien des Faches Sozialwissenschaften/Wirtschaftswissenschaft sind daneben Prob-lemorientierung, kategoriales Lernen, Kontroversität, Exemplarität, Fallprinzip, Schüler-, Handlungs-, Wissenschafts- und Zukunftsorientierung.
		
		Hilfestellungen für die Planung des Unterrichts sind: 
		­	Zur selbstständigen Analyse, Strukturierung und Reflexion brauchen die Schülerinnen und Schüler Kategorien. Identität, Institutionen, Verhandlung, Recht, Bedürfnis, Knappheit, Nutzen, Risiko, Wettbewerb sind zentrale Kategorien. Hieraus können Fragen des Unterrichts entwickelt werden, die mitunter nicht eindeutig zu beantworten sind. In einer zunehmenden Selbstständigkeit des Lernens verdichten sich diese Kategorien zu einer kognitiven Struktur.
		­	Die Verbindung zwischen schulischem und außerschulischem Lernen fördert durch die reale Begegnung besonders eine Verknüpfung von Abstraktem und Konkretem, methodischem sowie sozialem Lernen. Von besonderer Bedeutung sind hierbei der Besuch der Gerichte, öffentlicher Einrichtungen im soziologischen Kontext sowie die Verbindung zu Verbänden und Unternehmen.
